### ISSUE TITLE
IOM availability in UAE /QATAR region 

### ISSUE THREAD

**Issue by UmerBajwaD365** [MicrosoftDocs/dynamics-365-intelligent-order-management#11]
Is the IOM available in UAE/Qatar region?
If no,
what feature will not be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce84813b-5e99-11b2-4ae8-baa01f99c9cb
* Version Independent ID: 07a2295c-3ec5-74b7-a7ae-c23ef531766a
* Content: [Intelligent Fulfillment Optimization architecture](https://docs.microsoft.com/en-us/dynamics365/intelligent-order-management/ifo-arch)
* Content Source: [topics/ifo-arch.md](https://github.com/MicrosoftDocs/dynamics-365-intelligent-order-management-pr/blob/live/topics/ifo-arch.md)
* Service: **dynamics-365-intelligent-order-management**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by josaw1** [comment]
Thanks for your question. @rinitha-reddy can you please review?

**Comment by raybennett-msft** [comment]
Dynamics 365 Intelligent Order Management should be available in UAE. If you are experiencing otherwise please let me know 
so I can get more details.



> Is the IOM available in UAE/Qatar region? If no, what feature will not be available?
> 
Dynamics 365 Intelligent Order Management should be available in UAE. If you are experiencing otherwise please let me know 
so I can get more details.

Please also see these communities for support

[Yammer](https://yammer.com/dynamicsaxfeedbackprograms/ or the community forums for support )
[Dynamics Community Forums](https://community.dynamics.com/365/dynamics-365-intelligent-order-management/)

@josaw1 feel free to close

Thanks
Ray
